### ISSUE TITLE
Feature Request: let me choose the data directory

### ISSUE THREAD

**Issue by misterdelle** [stellitecoin/StelliteGUI#1]
Hi guys, I think that a very helpful feature is the possibility to the user to choose the data dir where to put the blockchain.
Normally other wallet client have some command line switches like -datadir.
This is extremely useful for users like me with a notebook with a limited SSD HD (250 GB) but with plenty of space in external drives.
And you know (and all we hope so) the blockchain can grow a lot in size.

**Comment by stellitecoin** [comment]
Feature present in latest release
