### ISSUE TITLE
Win 64 GUI wallet does not update with new balance

### ISSUE THREAD

**Issue by goldenlefteye** [stellitecoin/StelliteGUI#10]
Transaction ID is 81e4e6a17ae91e79a180186a1ccd291e7e49d7dc06367fac25d749c415980768
wallet synced to 123322/123322 (100.0%) on mainnet
still balance is 0. please advise. Your input is greatly appreciated. Thanks.

**Comment by Fubi118** [comment]
Same problem here...
Transaction ID: 645eddc8bcdf522181019eb9e98f2a8179b2683fd82f819c2b540bdd754e453a
wallet synced to 124035/124035 (100.0%)
balance still 0

I tried to get some information with "print_tx <tx hash>" but i got no output.

Thank you for your help!

**Comment by goldenlefteye** [comment]
The following is the reply from CREX24 support. everything looks set from their end. Issue is with the wallet.
      txid: 81e4e6a17ae91e79a180186a1ccd291e7e49d7dc06367fac25d749c415980768
      Amount of XTL: 70448,00000000
      Reciever's Public Address: Se2uLexsQZAMdLLXy4v7Eo7nwQ7QgCh2u38er3SumK51NniiHoqG7X7NsiL5Y2fwrzfc5rWVZxWBVUFeNJm8uihx1yed79pyZ
      Transaction Date and time: 20.04.2018 03:02:22

      Operation to be performed: Sync your wallet.

I have verified the address. it is indeed mine. The wallet still shows balance 0. I was going to buy more XLT this weekend, but after this experience I am definitely going to reconsider.

**Comment by Fubi118** [comment]
I found a Solution.
You have to do a restore of your wallet with the Wallet Mnemonic seed.
Her the steps i did:
1. Open your Wallet
2. Click on Settings
a. click on "Show seed & keys" and copy your seed
b. close your Wallet
3. Open the GUI Wallet again and choose Restore (with Mnemonic seed)
4. Your Wallet will sync again
5. Done! Now your balance should be fine.
It´s already documented here https://wiki.stellite.cash/books/stellite-wallets/page/known-issues

It works for me. My Balance is now correct.


I hope it will solve your problem as well.

**Comment by goldenlefteye** [comment]
Yes that worked. Thanks.

**Comment by 555green** [comment]
Hello, How can i choose restore when i open my GUI wallet? I do not have that option. Maybe a screenshot would help.
Thank you
