### ISSUE TITLE
customise path where blockchain is stored

### ISSUE THREAD

**Issue by basmoorkens** [stellitecoin/StelliteGUI#14]
I would like to propose a feature where there is an option in the wallet to choose the path of the blockchain files. At the moment it defaults to a standard directory on my c drive and this drive is a lot smaller then some of my other drives.

**Comment by Endogen** [comment]
If you are lucky, someone in the Monero community will add this if you create an issue [here](https://github.com/monero-project/monero-gui) and then Stellite developers can add it also.

**Comment by Endogen** [comment]
Actually, you don't even need to create that issue there. Take a look [here](https://monero.stackexchange.com/questions/3086/how-to-change-location-of-the-blockchain-with-monero-gui)

The wallet already has the ability to do that
