### ISSUE TITLE
Unable to start GUI wallet on Ubuntu 17.10

### ISSUE THREAD

**Issue by Ossii** [stellitecoin/StelliteGUI#16]
./start-gui.sh 
./stellite-wallet-gui: symbol lookup error: /home/osiris/Stellite-GUI-linux-x64-V0.0.8-1/qml/QtQuick/Dialogs/libdialogplugin.so: undefined symbol: _ZN18QFileDialogOptionsC1Ev

**Comment by mkrufky** [comment]
same issue with 18.04 LTS:
```
~/stellite/Stellite GUI Wallet 1.0.0$ ./start-gui.sh 
app startd
./stellite-wallet-gui: symbol lookup error: /home/mk/stellite/Stellite GUI Wallet 1.0.0/qml/QtQuick/Dialogs/libdialogplugin.so: undefined symbol: _ZN18QFileDialogOptionsC1Ev
```

**Comment by Ossii** [comment]
Nothing from devs at all?

**Comment by NoreiT** [comment]
Same with new 1.0.2 wallet?

**Comment by mkrufky** [comment]
Indeed, same issue with new 1.0.2 wallet:
```
StelliteGUI-linux-x64-1.0.2$ ./start-gui.sh 
app startd
./stellite-wallet-gui: symbol lookup error: /home/mk/stellite/StelliteGUI-linux-x64-1.0.2/qml/QtQuick/Dialogs/libdialogplugin.so: undefined symbol: _ZN18QFileDialogOptionsC1Ev
```

**Comment by AngeGallego** [comment]
Can you try installing the missing plugin `qml-module-qtquick-dialogs`

**Comment by mkrufky** [comment]
That plugin is already installed, at least on my system:
```
sudo apt-get install qml-module-qtquick-dialogs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qml-module-qtquick-dialogs is already the newest version (5.9.5-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libqwt-headers libqwt-qt5-6 linux-headers-4.15.0-23 linux-headers-4.15.0-23-generic linux-image-4.15.0-23-generic
  linux-modules-4.15.0-23-generic linux-modules-extra-4.15.0-23-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

mk@vujade:~/stellite/StelliteGUI-linux-x64-1.0.2$ ./start-gui.sh 
app startd
./stellite-wallet-gui: symbol lookup error: /home/mk/stellite/StelliteGUI-linux-x64-1.0.2/qml/QtQuick/Dialogs/libdialogplugin.so: undefined symbol: _ZN18QFileDialogOptionsC1Ev
```

**Comment by Hardslog** [comment]
Run this in the terminal to get the rest of the missing pieces:
`sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-xmllistmodel qttools5-dev-tools qml-module-qtquick-dialogs qml-module-qt-labs-settings qml-module-qtquick-controls2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel`

**Comment by mkrufky** [comment]
I apparently already have all of those packages installed.  So, unfortunately, still not the answer:
```
mk@vujade:~/stellite/StelliteGUI-linux-x64-1.0.2$ sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-xmllistmodel qttools5-dev-tools qml-module-qtquick-dialogs qml-module-qt-labs-settings qml-module-qtquick-controls2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel

Reading package lists... Done
Building dependency tree       
Reading state information... Done
qtbase5-dev is already the newest version (5.9.5+dfsg-0ubuntu1).
qml-module-qt-labs-folderlistmodel is already the newest version (5.9.5-0ubuntu1).
qml-module-qt-labs-settings is already the newest version (5.9.5-0ubuntu1).
qml-module-qtquick-controls is already the newest version (5.9.5-0ubuntu1).
qml-module-qtquick-controls2 is already the newest version (5.9.5-0ubuntu2).
qml-module-qtquick-dialogs is already the newest version (5.9.5-0ubuntu1).
qml-module-qtquick-xmllistmodel is already the newest version (5.9.5-0ubuntu1).
qt5-default is already the newest version (5.9.5+dfsg-0ubuntu1).
qtdeclarative5-dev is already the newest version (5.9.5-0ubuntu1).
qttools5-dev-tools is already the newest version (5.9.5-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libqwt-headers libqwt-qt5-6
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 117 not upgraded.
mk@vujade:~/stellite/StelliteGUI-linux-x64-1.0.2$ ./start-gui.sh 
app startd
./stellite-wallet-gui: symbol lookup error: /home/mk/stellite/StelliteGUI-linux-x64-1.0.2/qml/QtQuick/Dialogs/libdialogplugin.so: undefined symbol: _ZN18QFileDialogOptionsC1Ev
```

**Comment by stellitequestion** [comment]
can you try out this version:
https://github.com/stellitecoin/StelliteGUI/releases/download/v1.0.2/StelliteGUI-build-Ubuntu18.tar.xz
and let us know if that resolves any issues.

**Comment by Hardslog** [comment]
I run the app like this:

sudo ./stellite-wallet-gui

And it runs fine for me on 18.04 after installing the packages.

**Comment by stellitequestion** [comment]
tested it out with a clean ubuntu install no deps installed got an error.
![screenshot_8](https://user-images.githubusercontent.com/37975719/43036121-3b1f121c-8cfb-11e8-9ffe-4176e454ba5d.png)
then did:

sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel qttools5-dev-tools

after that I was able to load the wallet via ./start-gui.sh

**Comment by stellitequestion** [comment]
I used this version btw: https://github.com/stellitecoin/StelliteGUI/releases/download/v1.0.2/StelliteGUI-linux-Ubuntu18-x64-1.0.2.tar.gz

**Comment by mkrufky** [comment]
I didn't see the `https://github.com/stellitecoin/StelliteGUI/releases/download/v1.0.2/StelliteGUI-linux-Ubuntu18-x64-1.0.2.tar.gz` tarball specifically for Ubuntu18 !!  I was using the other Linux 1.0.2 build.   I bet that will fix the issue for me.  I'll post again tonight when I can give it a try.

**Comment by stellitequestion** [comment]
just dont forget:

sudo apt install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel qttools5-dev-tools


it has qml-module-qtquick-controls2 included which I didn't see in your linked list.

**Comment by mkrufky** [comment]
it's there.  see https://github.com/stellitecoin/StelliteGUI/issues/16#issuecomment-406768592

**Comment by stellitequestion** [comment]
true I see it.
fingers crossed this Ubuntu18 compile will solve your issues so keep us posted.

**Comment by mkrufky** [comment]
https://github.com/stellitecoin/StelliteGUI/releases/download/v1.0.2/StelliteGUI-linux-Ubuntu18-x64-1.0.2.tar.gz is incorrectly labelled as a `tar.gz` but it is actually a `tar.xz` ... please fix that.

Yes, this build works :-D

**Comment by stellitequestion** [comment]
Awesome good to hear I will close the ticket.

**Comment by NoreiT** [comment]
Hi, best thing to do is to come to our discord, easier to troubleshoot. but you should start to try run wallet from linux command line, I do expect you have some modules missing (usually QT libraries)

https://discord.gg/AnWFhJs
