### ISSUE TITLE
Daemon status not reflected correctly in GUI?

### ISSUE THREAD

**Issue by Endogen** [stellitecoin/StelliteGUI#21]
I'm on a Mac with GUI wallet 1.2.4.2 Titanium V3

The wallet syncs perfectly (i'm using a remote node) but what is strange is that under `Settings`  i can press `Start daemon` and `Stop daemon` is disabled. I think this is strange since the wallet syncs after start perfectly but then i would expect the opposite: button `Start daemon` disabled and `Stop daemon` enabled.

I believe that the daemon is started correctly but that the buttons are wrong.

![wallet](https://user-images.githubusercontent.com/226475/42138445-ebd490a6-7d7d-11e8-87f6-32698a2d773b.png)

If i press the `Start daemon` button, i get this error:

```
Please check your wallet and daemon log for errors. You can also try to start stellited manually.
```

Button `Show status` gives me an empty dialog

**Comment by stellitequestion** [comment]
will be fixed in updated macOS wallet release

**Comment by Endogen** [comment]
Thanks, will reopen if still not fixed in new version once i've tested it

**Comment by stellitequestion** [comment]
the version now on github is the latest compile can you test it out?

**Comment by Endogen** [comment]
The version i am using is the currently newest version available.

Version in first post of bug report: 1.2.4.2 Titanium V3
Newest currently available version: 1.2.4.2 Titanium V3

Not sure why you guys don't use the same version number everywhere.
Newest GUI wallet version: 1.2.4.2 Titanium V3
Newest release notes version: 1.0.2 'Titanium v3'

And it's actually bot the same

**Comment by Endogen** [comment]
Sorry didn't want to reopen

**Comment by stellitequestion** [comment]
yes but did you redownload it? the version now on github is without the blockchaindownload tool correct?
it's updated but not with a version change.

**Comment by Endogen** [comment]
`it's updated but not with a version change`

You are actually scaring me... Please never release changed software with the same version number

I redownloaded it. It's the version without the downloader yes. It's different now:
![bildschirmfoto 2018-07-23 um 21 29 07](https://user-images.githubusercontent.com/226475/43098479-96252550-8ebf-11e8-85c8-84aefbc1e65a.png)

It's still the same basic problem but button `Show status` is working now

**Comment by stellitequestion** [comment]
can you change daemon adress to localhost then do start daemon?

**Comment by Endogen** [comment]
sure, but then it will download the blockchain and that's not what i want

**Comment by stellitequestion** [comment]
if you want to press start daemon you need to use the localhost else its the remote node to connect without the blockchain file.

**Comment by Endogen** [comment]
the issue is that i can press the button `Start daemon` even tho i use a remote node. that makes no sense and that's why i opened this issue.

`Start daemon` should be disabled and `Stop daemon` enabled if i use a remote node. At least that's my understanding

**Comment by stellitequestion** [comment]
yes in that case you have a point but can you test:
stop daemon if possible
localhost
start daemon
check if its syncing
then stop daemon so see if it stops
then reconnect to nodes.stellite.cash not via connect but via start daemon - does that work?

**Comment by Endogen** [comment]
I can't stop it actually and i don't want to play around with it since it's otherwise working good :-)
