### ISSUE TITLE
My wallet is empty!

### ISSUE THREAD

**Issue by remark23** [stellitecoin/StelliteGUI#23]
Hello,

somebody blew my wallet, about 100.000 XTL.  
How is it possible? I have Tx ID, can something be done?

**Comment by stellitequestion** [comment]
There is no option to return coins once they have been send.
Only thing you could try - if it would even work - do you still have your 25 words for restore?
if so rename the stellite folder in your documents and startup the wallet it will ask for import / restore via seed words. do that and what till its done if the coins are not showing after its fully synced they are gone.

**Comment by AngeGallego** [comment]
To add on what @stellitequestion said, thsi si most likely cause by your security being compromised. This can be caused for example by installing malicious softwares

**Comment by remark23** [comment]
I have 25 words and try to restore my wallet. 
If that fails, what can I do? Open a new wallet and how to protect myself?

**Comment by Endogen** [comment]
make sure that noone except you can access the wallet (or the computer with that wallet) and that noone knows the mnemonic seed and the private key
