### ISSUE TITLE
GUI Wallet 1.0.2

### ISSUE THREAD

**Issue by OrexWhitefire** [stellitecoin/StelliteGUI#25]
I just downloaded this and when I click to run it for the first time it will pop up on my task bar then poof it's gone right away and stop running.  I checked and made sure it is not being blocked by Windows Defender and it's not, it actually on he approved list of apps.

What am I missing?

**Comment by BushMasterSix** [comment]
I 2nd this.... no use the wallet is broken... all features in win Defender deactivated and wont work. tried on last four versions. FIX THIS!
P.S. missing 32 bit version.

**Comment by Endogen** [comment]
The wallet is not broken! The issue is on the user-side IMO. Works perfectly for me

**Comment by jmxx2** [comment]
Having same issue, was working up until a couple das ago.  Log says
2018-10-01 14:22:11.331	8156	ERROR	WalletAPI	src/wallet/api/wallet.cpp:504	Error opening wallet: invalid password

password screen never come up tho.  Tried reinstalling but same result.

**Comment by jeffreyroberts** [comment]
I dunno, seems broken to me...

2018-10-07 01:37:33.510	2304	INFO 	logging	contrib/epee/src/mlog.cpp:148	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO

**Comment by NoreiT** [comment]
New wallet released since than, please try.
