### ISSUE TITLE
Stellite Daemon as a permanent service conflict with Monero Daemon  in Windows 10 x64 

### ISSUE THREAD

**Issue by Sassenio** [stellitecoin/StelliteGUI#26]
OS: Windows 10 x64
Task: Install Stellited.exe daemond as a permanent running service.

Problem: Installing Stellited Titanium V3 (V1.2.4.2-release) as a service  conflit with  Monero Lithium Luna (v0.12.3.0-release) Daemon service. The daemond work well alone. 

Tips: The Stellited.exe Daemon is installing as a service with 'Monero' as the service name.

![inkedstellited_li2](https://user-images.githubusercontent.com/37756235/46572055-b15b1000-c94d-11e8-9541-42806240c722.jpg)

**Comment by Endogen** [comment]
Not really sure since i didn't look into that but isn't this just a problem because you use the same port?
