### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by pttdev** [stellitecoin/StelliteGUI#27]
I ran into this issues. I tried many guide found on stackoverflow but can't make it to work.

This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
./start-gui.sh: line 7: 18490 Aborted                 (core dumped) "$SCRIPT_DIR"/stellite-wallet-gui

**Comment by NoreiT** [comment]
New wallet released since than, please try.
