### ISSUE TITLE
GUI Wallet not Syncing Blockchain

### ISSUE THREAD

**Issue by blackparallax** [stellitecoin/StelliteGUI#28]
Blockchain is not syncing, file size on 76KB. Wallet balance is correct but why is the blockchain not syncing??

I am using Stellite GUI Wallet v1.0.2 on Windows 64bit.

![20181109_133047](https://user-images.githubusercontent.com/14051589/48241689-b36c2f00-e423-11e8-8cf3-2b802ca4490d.jpg)

**Comment by Endogen** [comment]
Do you use a remote node? If not, try using it:
1. Settings --> Daemon address: `daemons.cryptopool.space`
2. Port: `20189`

Wait a little bit and see if it synchronizes
