### ISSUE TITLE
Remote node uses monero default port

### ISSUE THREAD

**Issue by snider** [stellitecoin/StelliteGUI#42]
The GUI when entering the node details will auto-fill the monero port when you move out of the application.

1) enter the host
![image](https://user-images.githubusercontent.com/631881/51785158-8b02ef80-214b-11e9-83c9-db6855d91586.png)
2) switch to another app and back to see the port filled in (in my case on a mac i swiped to another workspace to copy the port)
![image](https://user-images.githubusercontent.com/631881/51785169-b1288f80-214b-11e9-8892-227b7e5bb72e.png)

**Comment by NoreiT** [comment]
thanks, will be addressed in 2.0.0.1
