### ISSUE TITLE
Win10 64 Stellite V.08 Gui Wallet Status Disconnected

### ISSUE THREAD

**Issue by kryptogainz** [stellitecoin/StelliteGUI#8]
I just downloaded the New Stellite V.08 Gui Wallet for windows 10 64. The status says disconnected and no daemon connection. Can someone please help me solve this problem.
Thank you

**Comment by 777crypto777** [comment]
me too .

**Comment by kryptogainz** [comment]
Download the V.08 and you will be good as that's what I did and now seeing coins in my wallet.
