### ISSUE TITLE
Dutch translations are are not correct

### ISSUE THREAD

**Issue by basmoorkens** [stellitecoin/StelliteGUI#9]
When I wanted to import my paper wallet I noticed in the wizard that in several instances u was used instead of uw. This is wrong spelling in dutch and does not look very professional.

**Comment by hayzamjs** [comment]
You can make a PR to the repo with the corrections 👍
Thank you

**Comment by basmoorkens** [comment]
I dont have the rights to push a branch to github. I dont know any way to create a pull request without pushing a branch with my changes first. Can you provide me with push permissions?

**Comment by hayzamjs** [comment]
You can fork the repo and add the modifications on your repo and make a pull request, [here's](https://yangsu.github.io/pull-request-tutorial/) an awesome page to help you out

**Comment by basmoorkens** [comment]
Thx for the explanation, I had never forked a repo before. the pull request is awaiting confirmation :)
